//MSCHAT 2.1 last update 10/30/97

#define IDH_REALNAME            1
#define IDH_NICKNAME            5
#define IDH_PROFILE             10
#define IDH_TOPIC               15
//#define IDH_AUDITORIUM          20
#define IDH_MODERATED           25
#define IDH_SET_TOPIC           30
#define IDH_INVITE              35
#define IDH_HIDDEN              40
#define IDH_PRIVATE             45
#define IDH_SET_MAX             50
//#define IDH_NO_WHISPERS         55
#define IDH_LAYOUT              60
#define IDH_NO_GRAPHX           65
#define IDH_PROMPT_TO_SAVE      70
#define IDH_ACCEPT_WHISPERS     75
#define IDH_CHAR_LIST           80
#define IDH_CHAR_PRVW           85
#define IDH_EMOTION_WHEEL       90
#define IDH_FONT                95
#define IDH_STYLE               100
#define IDH_SIZE                105
#define IDH_SAMPLE              110
#define IDH_SCRIPT              115
#define IDH_BKG_LIST            120
#define IDH_PRVW_BKG            125
#define IDH_SEARCH              130
#define IDH_SEARCH_TOPICS       135
#define IDH_UPDATE              140
#define IDH_GOTO                145
#define IDH_NEW_ROOM            150
#define IDH_FAVORITES           155
#define IDH_SERVER              160
#define IDH_CHAT_ROOM           165
#define IDH_SHOW_ALL            170
#define IDH_NICK_INVITE         175
#define IDH_KICK_COMMENT        180
#define IDH_ALSO_BAN            185
#define IDH_NICK_BAN            190
#define IDH_BAN					195
#define IDH_UNBAN				200
#define IDH_SOUND_PATH          205
#define IDH_SHOW_ARRIVALS       210
#define IDH_ALL_MSGS            215
#define IDH_DIFF_MSGS           220
#define IDH_NO_BLANKS           225
#define IDH_CHANGE_FONT         230
#define IDH_RESET_FONT          235
#define IDH_HOST_HEADERS        240
#define IDH_HOST_BOLD           245
#define IDH_ALL_USER            250
#define IDH_USER_UPDATE         255
#define IDH_SEARCH_NICKNAME     260
#define IDH_IDENTITY            265
#define IDH_USER_INVITE         270
#define IDH_WHISPER_BOX         275
//#define IDH_WHISPER             280
//#define IDH_IGNORE              285
//#define IDH_END_WHISPER         290
#define IDH_STRIKEOUT           295
#define IDH_UNDERLINE           300
#define IDH_FONT_COLOR          305
#define IDH_SHOW_TYPES          310
#define IDH_MSG_TYPE            315
#define IDH_SOUNDS              320
#define IDH_SOUND_MSG           325
#define IDH_TEST_SOUND          330
#define IDH_ACCEPT_INVITE       335
#define IDH_AUTO_NONE           340
#define IDH_AUTO_WHISPER        345
#define IDH_AUTO_SAY            350
#define IDH_AUTO_TEXT           355
#define IDH_MACRO_KEY           360
#define IDH_MACRO_TEXT          365
#define IDH_MACRO_NAME          370
#define IDH_MACRO_ADD           375
#define IDH_MACRO_DELETE        380
#define IDH_OPTIONS_PERSINFOTAB_EMAIL     385
#define IDH_OPTIONS_PERSINFOTAB_WEBPAGE   390
#define IDH_OPTIONS_SETTINGS_GETID        395
#define IDH_OPTIONS_SETTINGS_PLAYSOUNDS   400
#define IDH_OPTIONS_SETTINGS_REC_NETMEET  405
#define IDH_ROOMLIST_SHOW_ONLY_REG        410
#define IDH_ROOMLIST_MEMBERS_MIN          415
#define IDH_ROOMLIST_MEMBERS_MAX          420
#define IDH_CREATEROOM_CHATROOM_NAME      425
#define IDH_CREATEROOM_OPTIONAL_PASSWORD  430 
#define IDH_OPTIONS_SETTINGS_DCC          435
#define IDH_OPTIONS_COMICSVIEW_RTF        440
#define IDH_OPTIONS_AUTOMATION_FLOODERS   445
#define IDH_OPTIONS_AUTOMATION_MSGCOUNT   450
#define IDH_OPTIONS_AUTOMATION_INTERVAL   455
#define IDH_USERLIST_JOINUSER             460
#define IDH_VIEW_MESSAGEOFDAY             465
#define IDH_VIEW_MSGOFDAY_ONCONNECT       470
#define IDH_OPTIONS_TEXTVIEW_HEADERSMSGS  475
#define IDH_GROUP_ID                      485
#define IDH_MEMBER_AWAY                   490
#define IDH_SETTINGS_CONTENT_ADVISOR      495  
#define IDH_SETTINGS_ENABLE_RATINGS       500
#define IDH_SETTINGS_SETTINGS_BUTTON      505
#define IDH_ROOMLIST_HEADINGS             510
#define IDH_USERLIST_HEADINGS             515
#define IDH_SETTINGS_INVISIBLE            520


