#ifndef __PROTSUPP_H__
#define __PROTSUPP_H__

#include "roomlist.h"
#include "userlist.h"
#include "ircsock.h"

extern CNCSMapStringToPtr*	g_mapNickToPtr;
extern CPtrArray			g_rgpuiWhisperees;
extern CRoomInfo			g_enterInfo;
extern CRoomInfo*			currentRoom;
extern SHORT				g_nCXKeepServer;
extern BOOL					g_bCXPrompt;
extern BOOL					g_bFreezeTabs;
extern BOOL					g_bEnterOnCreate;

char *GetToken(char *szStart, char **pszNextStart, const char *szSeps = ",.)", char **pszCurStart = NULL);
char *GetToken1(char *szStart, char **pszNextStart, const char *szSepsEnd, char **pszCurStart = NULL, BOOL bSkipInitialSeps = TRUE);
char *GetToken2(char *szStart, char **pszNextStart, const char *szSepsBegin, const char *szSepsEnd, char **pszCurStart = NULL);
BOOL bReplaceMacroTokens(CString &strMessage, BOOL bIn);
BOOL ReplaceToken(CString& str, const CString& strToken, const CString& strValue);
BOOL ToggleSendComicsData();
void SetSendComicsData(BOOL bSendComicsData);
BOOL GetSendComicsData();
void ChatSetCXPrompt(BOOL bPrompt);
BOOL GetCXPrompt();
BOOL ChatInitialize(SHORT *pnCXKeepServer, BOOL *pbCXPrompt);
void AdjustViewMode();
void SetArtDir(const char *artDir);
void ChatEmptyMemberList(CChatDoc *doc = NULL);
void DestroyUserInfos(CChatDoc *doc);
void DestroyExternalUserInfos();
BOOL bForEachWord(char *szLine, BOOL (*pfn)(char *, void *, DWORD), void *pvClientData, DWORD dwClientData, char *szSep, BOOL bDoubleQuotes = FALSE);
void AddToMembersList(CUserInfo *pui, CChatDoc *doc = NULL);
void AssignArbitraryAvatar(CUserInfo *pui);
CUserInfo *LookupPui(const char *szNickname, CChatDoc *doc = NULL);
CUserInfo *ExternalPui(const char *szNickname, const char *szFullName, BOOL bAddIfNotThere = FALSE);
USHORT GetAvatarIDFromNickname(LPCTSTR nickname);
CUserInfo *CIUserJoin(CUserInfo *pui);
int AddToImageList(CUserInfo* pui);
int FindMemberListIndex(CUserInfo *pui, CChatDoc *doc = NULL);
int RemoveMemberFromList(CUserInfo* pui);
void CIUserPart(const char *nickname);
void CopyPtrArrayToCWDordArray(CPtrArray &source, CDWordArray &dest);
void CopyArray(CDWordArray &source, CDWordArray &dest);
BOOL ExpandVariables(CString &strMessage, CChatDoc *doc, CUserInfo *pui = NULL, BOOL bInvokedByRule = FALSE);
void AutoGreet(const char* szNick);
BOOL ProcessComment(CChatDoc *doc, CUserInfo *pui, char *szMesg, BYTE msgType);
BYTE IndexToByte(BYTE byteIn);
BYTE ByteToIndex(BYTE byteIn);
USHORT SM2BM(BYTE byteMode);
BYTE BM2SM(USHORT uModes);
void GetTalkTos(CChatDoc *doc, CUserInfo *talkerPui, char *str);
void GetTalkTos(CChatDoc *doc, CDWordArray *talkTos, char *str);
char *PrepareTextAction(CUserInfo *pui, char *szMesg, CString &strNewMesg, USHORT &uModes);
char *PrepareComicsAction(CUserInfo *pui, char *szMesg, CString &strNewMesg);
void ShowVersion(CUserInfo *pui, CString strMesg);
void ShowPing(CUserInfo *pui, const char *mesg);
void ShowTime(CUserInfo *pui, CString mesg);
void ShowEmail(CUserInfo *pui, CString strAddress);
void ShowHomePage(CUserInfo *pui, CString strURL);
void ShowAway(CUserInfo *pui, CString strAwayMsg, CChatDoc *doc);
void _cdecl ConfConnect(void *arg);
void LaunchMicrosoftURL(UINT resourceID);
void _cdecl ConfListenThread(void *);
char* PrepareSound(CUserInfo *pui, char *szMesg, CString &strNewMesg, USHORT &uModes);
void CheckForSelf(char *name, void *myName);
void IdentifyWhispers(CChatDoc *doc, CUserInfo *pui, BYTE msgType, USHORT &uModes, CDWordArray *talkTos);
BOOL AcceptWhispers();
void ProcessUDIData(CChatDoc *pDoc, CUserInfo *pui, char *szData);
void ProcessSay(CChatDoc *doc, CUserInfo *pui, char *szMesg, BYTE msgType, CDWordArray *talkTos);
void OnKick(CChatDoc *pDoc, char *szKicker, char *szKickee, char *szMesg);
void PreMemberNameChange(CChatDoc *doc, CUserInfo *pui, LV_ITEM &item);
void PostMemberNameChange(CChatDoc *doc, CUserInfo *pui, LV_ITEM &item);
void ReinstallPui(CUserInfo *pui, const char *newNick);
void ProcessNick(CChatDoc *doc, const char *oldNick, const char *newNick, BOOL updateMemberList);
void ChatChangeAdmin(CChatDoc *doc, const char *szNickname, int setModes, int unsetModes);
void AddIgnore(const char *nickMask);
void RemoveIgnore(const char *nickMask);
BOOL IsIgnored(const char *nickMask);
void UpdateIgnoreOnEntry(const char *room, const char *nick, const char *user, const char *host);
void IgnoreUser(const char *nick, const char *nickMask, BOOL bIgnore, BOOL bAutoIgnore);
void DoUserAway(CChatDoc *doc, CUserInfo *pui, BOOL bAway);
void ListMembers(const char *szRoom, const char *szPrettyRoom);
void GetAddressees(CUserInfo *pui, const char *szSeparator, CString &str, BOOL bUseNick);
void GetWhisperedAddressees(const char *szSeparator, CString &str);
void ProcessNonComicsMsg(CString &str, USHORT &uModes);
BOOL bChatSendText(CString& str, USHORT uModes, BOOL bEcho = TRUE, CDWordArray* prgdwFormatting = NULL, LPCTSTR szEncodedChannelName = NULL, BOOL bWhispereesFilled = FALSE, BOOL bInvokedByWhisperBox = FALSE);
BOOL bChatSendSound(const char *szSnd, const char *szMesg, CDWordArray *prgdwFormatting, BOOL bEcho, USHORT uModes, LPCTSTR szEncodedChannelName = NULL);
BOOL bCanViewUnrated(BOOL bPromptOverride = FALSE);
BOOL bRatingsEnabled();
BOOL bNMInstalled();
extern BOOL g_bCanViewUnrated;			// cached during room list
void StartRoomList();
void EndRoomList();
void EndUserList();
void AddToRoomList(CRoom *pRoom, BOOL bAddIt = TRUE);
void AddToUserList(CUser *pUser);
void ShowIdentity(const char *nick, const char *user, const char *host);
void DoBanDlg(const char *szEncodedChannelName, const char *szBan, CStringArray &banArray);
BOOL bDoInvite(char *szInvitee, void *pvProto, DWORD dwData);
BOOL bSendPrivMsg(char *szReceiver, void *pvTextMessage, DWORD dwInvokedByWhisperBox);
void RepopulateMemberList();
void MapNullAvatars(CChatDoc *doc);
void InitializeChannelConnection(CRoomInfo& enterRoom, SHORT *pnCXKeepServer, BOOL *pbCXPrompt, BOOL bCreateRoom);
void AdjustFlags(DWORD oldMode, BOOL newVal, UINT field, DWORD *setMask, DWORD *unsetMask);
void ChatSwitchChannel(const char *szChannelName);
void ShowBadChannelName(const char *szChannelName);
BOOL bInitEnterInfo(CRoomInfo& enterInfo, const char *szChannelName, const char *szChannelPassword, const char *szCreationModes, DWORD dwMaxUsers, BOOL bEncodeChan);
void ChatCreateRoom(CRoomInfo& enterInfo);
BOOL bProcessAddChannel(const char *szChanName, CRoomInfo *proto, SHORT *pnCXKeepServer, BOOL *pbCXPrompt);
void ActivateWindow(CChatDoc *doc);
void OnPart(char *nick);
void OnNewNick(char *oldNick, char *newNick);
CUserInfo* PuiFromDocNickIdent(CChatDoc **ppDoc, char *szNickname, const char *szUserIdent, BOOL bSkipObscuredChannels, BOOL bAddExternalIfNotThere);
void OnTextMsg(CChatDoc *doc, char *szNickname, const char *szUserIdent, char *szMesg, BYTE msgType = MT_CHANNELSEND|MT_PRVMSG, CDWordArray *talkTos = NULL);
void OnDataMsg(CChatDoc *pDoc, char *szNickname, const char *szUserIdent, char *szData, BYTE msgType = MT_CHANNELSEND|MT_DATA);
void ProcessBeginEnumeration();
void ProcessEndEnumeration();
BOOL bPassesRatings(const char *szRating, BOOL bPromptOverride = FALSE);
BOOL bSwitchToRoom(const char *szNewRoom, const char *szPassword = NULL, const char *szCreationModes = NULL, DWORD dwMaxUsers = 0L, BOOL bEncodeChan = FALSE, BOOL bCreateRoomInfo = FALSE, BOOL bCreateRoom = FALSE);
void OnInvite(const char *szSender, const char *szFullName, const char *szRoom);
BOOL ConvertEncodingIn(LPSTR *pszStr);
BOOL ConvertEncodingOut(LPSTR *pszStr);
void OnBadChannelPassword(CRoomInfo& enterInfo);
BOOL bCanDance();
void GotPartChannel(CChatDoc *doc);
void OfflineEditInits();
void ChatServerDisconnect(BOOL bCheckRules = FALSE, BOOL bResumeConnection = FALSE);
BOOL bChatServerConnect(const char *szServer);
void InitializeServerConnection(CRoomInfo* pEnterInfo, BOOL* pbCXPrompt);
void ReconnectToServer(const char *szDecodedNickname, const char *szServerName);
int DoConnectDialog();
void ShowSay(CChatDoc *pDoc, CUserInfo *pui, const char *szText, CDWordArray *prgdwFormatting, BYTE bbCooked, USHORT uModes);
void AcknowledgeInvite(const char *szNickname, const char *szRoom);
void ConfirmAway(LPCSTR pszConditionallyOnText = NULL);
CUser* CreateUserFromWhoReply(IRCPARSE *pParse);
BOOL ChangeKeyString(CString &strKeyString, LPCSTR pszKey, LPCSTR pszValue, int nMaxSize);
BOOL GetValueFromKeyString(LPCSTR pszKeyString, LPCSTR pszKey, CString &strValueOut);
BOOL EnumKeyString(LPCSTR &pszKeyString, CString &strKey, CString &strValue);
CString StrGetSoundAction(CString strSoundFile, CString strTextMessage, CDWordArray* prgdwFormatting);

#endif
